# Generated by Django 5.1.6 on 2025-03-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_report_skinprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinprogress',
            name='image',
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='progress_images/'),
        ),
    ]
