# Generated by Django 5.1.6 on 2025-03-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skincareroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
